### PR TITLE
Add new rule to enforce correct imports of the SVG icons

### PR DESCRIPTION
**Pull request by filipsobol**
### Suggested merge commit message ([convention](https://github.com/ckeditor/ckeditor5-design/wiki/Git-commit-message-convention))

Feature (eslint-plugin-ckeditor5-rules): Add a rule to enforce correct imports of the SVG icons. See ckeditor/ckeditor5#15704.

---

### Additional information

*For example – encountered issues, assumptions you had to make, other affected tickets, etc.*

### CODE REVIEW

**Review by pomek — CHANGES_REQUESTED** [review]
Please, normalize paths to make sure the rule works on Windows paths too.

**Comment by filipsobol** [comment]
> Please, normalize paths to make sure the rule works on Windows paths too.

Which part exactly? The `url` variable will either be starting with a package name (`@ckeditor/...`) or be a relative path (`../...`). This `url` is split into parts using platform-specific path separator (`sep`), so it should work fine on Windows. Am I missing something?

**Comment by pomek** [comment]
You can verify if it works (as expected) by writing a test using Windows-like paths. If so, we do not need to update anything in sources.

**Comment by arkflpc** [comment]
Does the existing code conform to this rule? If no, it would be a breaking change (i.e. major version in order not to break `stable`).

**Comment by pomek** [comment]
It doesn't, but this PR only adds a new rule. It's enabled in CKE5 directly. So, stable should be fine.

**Comment by filipsobol** [comment]
> You can verify if it works (as expected) by writing a test using Windows-like paths. If so, we do not need to update anything in sources.

I just checked, and Windows-style forward slashes doesn't even seem to work in import and export paths. Note that we are dealing here with import paths, not file system paths.

**Comment by filipsobol** [comment]
> Does the existing code conform to this rule? If no, it would be a breaking change (i.e. major version in order not to break `stable`).

There's one import that doesn't conform to this rule, but as @pomek said, this rule only gets added. Turning it on is done is separate PRs (https://github.com/ckeditor/ckeditor5/pull/15705 and https://github.com/cksource/ckeditor5-commercial/pull/5928).

**Review by pomek — APPROVED** [review]
LGTM.

**Pull request merged**
